#ifndef NX_USER_H
#define NX_USER_H


#define NX_ENABLE_IPV6_ADDRESS_CHANGE_NOTIFY

#define NX_ENABLE_EXTENDED_NOTIFY_SUPPORT
#define NX_BSD_ENABLE_NATIVE_API
#define NX_BSD_RAW_SUPPORT
#define NX_SNTP_CLIENT_MIN_SERVER_STRATUM 10
#define NX_SNTP_CLIENT_MAX_ROOT_DISPERSION 0

#endif

